#!/bin/bash

export WINE_DEPS="libasound2:armhf libc6:armhf libglib2.0-0:armhf"
export WINE_DEPS+=" libgphoto2-6:armhf libgphoto2-port12:armhf"
export WINE_DEPS+=" libgstreamer-plugins-base1.0-0:armhf"
export WINE_DEPS+=" libgstreamer1.0-0:armhf libldap-2.5-0:armhf"
export WINE_DEPS+=" libopenal1:armhf libpcap0.8:armhf libpulse0:armhf"
export WINE_DEPS+=" libsane1:armhf libudev1:armhf libusb-1.0-0:armhf"
export WINE_DEPS+=" libvkd3d1:armhf libx11-6:armhf libxext6:armhf"
export WINE_DEPS+=" libasound2-plugins:armhf ocl-icd-libopencl1:armhf"
export WINE_DEPS+=" libncurses6:armhf libncurses5:armhf libcap2-bin:armhf"
export WINE_DEPS+=" libcups2:armhf libdbus-1-3:armhf libfontconfig1:armhf"
export WINE_DEPS+=" libfreetype6:armhf libglu1-mesa:armhf libglu1:armhf"
export WINE_DEPS+=" libgnutls30:armhf libgssapi-krb5-2:armhf libkrb5-3:armhf"
export WINE_DEPS+=" libodbc1:armhf libosmesa6:armhf libsdl2-2.0-0:armhf"
export WINE_DEPS+=" libv4l-0:armhf libxcomposite1:armhf libxcursor1:armhf"
export WINE_DEPS+=" libxfixes3:armhf libxi6:armhf libxinerama1:armhf"
export WINE_DEPS+=" libxrandr2:armhf libxrender1:armhf libxxf86vm1:armhf"


