#!/bin/bash

function usage
{
    echo -n "Usage: $(basename ${0}) <wine-staging_....deb>"
    echo    "<wine-staging-amd64_....deb>"
    echo ""
    echo "Example: $(basename ${0}) wine-staging_9.20~bookworm-1_amd64.deb "
    echo "         wine-staging-amd64_9.20~bookworm-1_amd64.deb"
    echo ""
    echo "This script will extract Wine and install it into your account"
    echo ".local folder."
    echo ""
    echo "The packages can be in any order because both are going to be"
    echo "extracted and their contents copied to ~/.local/wine"
    echo ""
}


function abort
{
    REASON=$1

    if ! [ "$REASON" == "" ];
    then
        echo "$REASON"
    fi

    echo ""

    exit 1
}


if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
    usage
    abort
fi




ARCH=$(uname -m)
PACKAGE_1=$1
PACKAGE_2=$2


if [ "$ARCH" == "arm64" ] && ! [ -f "/usr/local/bin/box64" ];
then
    echo "Box64 wasn't found in /usr/local/bin and it is needed for running"
    echo "Wine in ARM64 devices."

    abort
fi


echo ""
echo "Installing WINE..."
echo "=================="
echo ""

dpkg-deb -x $PACKAGE_1 "$HOME/.local/wine"

if ! [ "$?" == "0" ];
then
    abort "Failed extracting '$PACKAGE_1'."
fi


dpkg-deb -x $PACKAGE_2 "$HOME/.local/wine"

if ! [ "$?" == "0" ];
then
    abort "Failed extracting '$PACKAGE_2'."
fi


echo ""
echo "Finished."
echo ""



